import type { Metadata } from "next";
import "./globals.scss";
import Header from "@/components/Header";
import "fhf/dist/normalize.css";
import Footer from "@/components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import UserBtn from "@/components/UserBtn";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          <UserBtn />
          <EdgeStoreProvider>{children}</EdgeStoreProvider>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
